"""
PS&R (Provider Statistical & Reimbursement) Summary Parser.

The PS&R report is generated by Medicare's claims processing system
and contains the provider's Medicare utilization data — covered charges,
Medicare payments, deductible/coinsurance amounts, and beneficiary counts.

This parser handles:
- Text/PDF PS&R reports (common format from Medicare contractors)
- Tabular extracts from Medicare's HCRIS / claims data
"""

from __future__ import annotations

import io
import re
import time
from pathlib import Path
from typing import Any

from src.core.models import EntryType, GrossGLTransaction, ParsedIngestionResult
from src.ingestors.base_parser import BaseParser, sanitize_amount, sanitize_string


class PSRSummaryParser(BaseParser):
    """Parser for PS&R (Provider Statistical & Reimbursement) summaries."""

    entry_type = EntryType.PSR_SUMMARY

    def parse(self, content: bytes, source_file: str, **kwargs) -> ParsedIngestionResult:
        start_time = time.time()
        ext = Path(source_file).suffix.lower()
        errors: list[dict] = []

        try:
            if ext == ".pdf":
                rows = self._parse_pdf(content)
            elif ext in (".txt", ".text"):
                rows = self._parse_text(content)
            elif ext in (".csv", ".tsv"):
                rows = self._parse_tabular(content, ext)
            else:
                rows = self._parse_text(content)
        except Exception as e:
            elapsed = (time.time() - start_time) * 1000
            return ParsedIngestionResult(
                source_file=source_file,
                entry_type=self.entry_type,
                entries=[],
                row_count=0,
                error_count=1,
                errors=[{"row": 0, "error": f"PS&R parse failure: {e}"}],
                column_mapping={},
                processing_time_ms=round(elapsed, 2),
            )

        entries: list[GrossGLTransaction] = []
        for row in rows:
            try:
                acct_prefix = "PSR"
                entries.append(GrossGLTransaction(
                    account_number=sanitize_string(
                        row.get("revenue_code", f"{acct_prefix}-{row.get('service_type', 'GEN')}")
                    ),
                    account_description=sanitize_string(
                        row.get("description", row.get("service_type", "PS&R Summary"))
                    ),
                    debit_amount=sanitize_amount(row.get("covered_charges", row.get("amount", "0"))),
                    credit_amount=Decimal("0.00"),
                    period=sanitize_string(row.get("period", row.get("report_date", ""))),
                    source_file=source_file,
                    row_index=row.get("_row_index"),
                ))
            except Exception as e:
                errors.append({"row": row.get("_row_index"), "error": str(e)})

        elapsed = (time.time() - start_time) * 1000
        return ParsedIngestionResult(
            source_file=source_file,
            entry_type=self.entry_type,
            entries=entries,
            row_count=len(entries),
            error_count=len(errors),
            errors=errors,
            column_mapping={},
            processing_time_ms=round(elapsed, 2),
        )

    def _parse_pdf(self, content: bytes) -> list[dict]:
        """Extract PS&R data from PDF reports."""
        import pdfplumber

        rows: list[dict] = []
        with pdfplumber.open(io.BytesIO(content)) as pdf:
            full_text = ""
            for page in pdf.pages:
                full_text += (page.extract_text() or "") + "\n"

            return self._parse_psr_text(full_text)

    def _parse_text(self, content: bytes) -> list[dict]:
        """Parse plain-text PS&R summaries."""
        text = content.decode("utf-8-sig", errors="replace")
        return self._parse_psr_text(text)

    def _parse_psr_text(self, text: str) -> list[dict]:
        """Core PS&R text parsing logic — shared by PDF and text paths."""
        rows: list[dict] = []

        # Try to find tabular sections in the PS&R report
        lines = text.split("\n")
        row_idx = 0

        # Pattern 1: Look for lines with revenue codes and dollar amounts
        rev_code_pattern = re.compile(
            r"(?P<code>\d{4}[A-Z]?)\s+"
            r"(?P<desc>.{10,60}?)\s+"
            r"(?P<charges>[\d,]+\.?\d*)\s+"
            r"(?P<payments>[\d,]+\.?\d*)\s+"
        )

        # Pattern 2: Key-value pairs (common in text summaries)
        kv_pattern = re.compile(
            r"(?P<key>[A-Za-z\s/&-]+?):?\s{2,}(?P<value>[\d,]+\.?\d*)"
        )

        in_table = False
        for line in lines:
            row_idx += 1
            line_stripped = line.strip()
            if not line_stripped:
                in_table = False
                continue

            # Try revenue code pattern
            m = rev_code_pattern.search(line_stripped)
            if m:
                in_table = True
                rows.append({
                    "_row_index": row_idx,
                    "revenue_code": m.group("code"),
                    "description": m.group("desc").strip(),
                    "covered_charges": m.group("charges").replace(",", ""),
                    "payments": m.group("payments").replace(",", ""),
                })
                continue

            # Try key-value pattern if not in a table section
            if not in_table:
                m = kv_pattern.search(line_stripped)
                if m:
                    key = m.group("key").strip().lower().replace(" ", "_")
                    val = m.group("value")
                    rows.append({
                        "_row_index": row_idx,
                        "description": key,
                        "amount": val.replace(",", ""),
                    })

        return rows

    def _parse_tabular(self, content: bytes, ext: str) -> list[dict]:
        """Parse tabular PS&R data (CSV/TSV format from HCRIS extracts)."""
        import csv

        delimiter = "\t" if ext == ".tsv" else ","
        text = content.decode("utf-8-sig")
        reader = csv.reader(io.StringIO(text), delimiter=delimiter)
        rows: list[dict] = []

        try:
            headers = next(reader)
        except StopIteration:
            return rows

        headers = [h.strip().lower().replace(" ", "_") for h in headers]
        for row_idx, row in enumerate(reader, start=2):
            row_dict: dict = {"_row_index": row_idx}
            for col_idx, val in enumerate(row):
                if col_idx < len(headers):
                    row_dict[headers[col_idx]] = val.strip()
            rows.append(row_dict)

        return rows
